---
title: "Tidying Project Logbook"
output: html_notebook
---

```{r}
data <- read.csv('HbA1c2.csv') 
```

```{r}
proc_data <- data %>%
              mutate(Sex = 
                factor(
                  Sex, levels = c(0,1),
                  labels = c('Female','Male'))) %>%
              mutate(Group =
                       factor(
                         Group, levels = c(0,1),
                         labels = c('Control', 'Treatment'))) %>% print
```

```{r}
proc_data <- proc_data %>%
              mutate(Age_Cat =
               cut(Age,
               breaks = c(-Inf, 55, Inf),
               labels = c('0 - 55', '56+'),
               ordered_result = TRUE)) %>%
              mutate(BMI = Weight/((Height/100)**2)) %>%
              mutate(BMI_Cat = cut(BMI,
               breaks = c(-Inf, 18.5, 25, 29.9, Inf),
               labels = c('Low', 'Normal', 'Overweight', 'Obese'), ordered_result = TRUE))

col_order = c('id', 'Group', 'Sex', 'Age', 'Age_Cat', 'Weight', 'Height', 'BMI', 'BMI_Cat')

proc_data <- proc_data[, col_order] 
```
